# COULD SIMPLIFY WITH SOMETHING LIKE THIS: https://graha.ms/posts/blog/2023-05-08-esphome-autorestart/

esphome:
  name: plug-pm-1
  friendly_name: Plug (PM) 1
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
  on_boot:
    priority: -100
    then:
      light.turn_on:
        id: device_status_led

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

safe_mode:

logger:
  level: DEBUG
  logs:
    component: NONE
    esp-idf: WARN
    sensor: INFO

api:
  id: api_component
  reboot_timeout: 0s
  actions:
    - action: power_cycle
      then:
        script.execute: cycle_power

ota:
  platform: esphome
  password: "c9e550ec104cd83f1fcfef5dc5b108a2"
  on_end:
    then:
      - logger.log: "Switching relay off for 45 seconds before rebooting"
      - switch.turn_off: relay
      - delay: 45s
      - switch.turn_off: relay


captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Plug-Pm-1 Fallback Hotspot"
    password: "tpHfmEHr135L"
    ap_timeout: 30min

button:
  - platform: safe_mode
    name: Safe Mode

  - platform: restart
    name: Reboot Switch
    id: reboot_btn

  - platform: template
    name: Power Cycle
    id: power_cycle_btn
    device_class: restart
    on_press:
      then:
        - script.execute: cycle_power

# esp32_ble_tracker:

# bluetooth_proxy:
#   active: true


http_request:

# web_server: !remove

sensor:
  - platform: uptime
    type: seconds
    id: plug_uptime
    name: Plug Uptime
    internal: true

  # - platform: template
  #   id: testtesttest
  #   name: "Power Cycles"
  #   # state_class: total
  #   lambda: return 12.0;
  #   update_interval: 60s

globals:
  - id: last_power_cycle
    type: int
    restore_value: no
    initial_value: '0'

  - id: power_cycle_cnt
    type: int
    restore_value: no
    initial_value: '0'

  - id: failed_requests
    type: int
    restore_value: no
    initial_value: '0'

  - id: failed_requests_no_api_client
    type: int
    restore_value: no
    initial_value: '0'

interval:
  - interval: 1min
    startup_delay: 300s
    then:
      script.execute: make_http_request



# interval:
#   - interval: 1min
#     then:
#       - http_request.get:
#           url: https://www.google.com/generate_204
#           on_response:
#             then:
#               # - lambda: |-
#               #     //ESP_LOGD("main", "response status %f", x->status_code);
#               #     ESP_LOGD("main", "failed requests %f", id(failed_requests).state);
#               - logger.log:
#                   level: DEBUG
#                   format: 'Response status: %d, Duration: %u ms'
#                   args:
#                     - response->status_code
#                     - response->duration_ms
#               - if:
#                   condition:
#                     lambda: 'return id(failed_requests).state > 0;'
#                   then:
#                     - logger.log:
#                         level: INFO
#                         format: "Successful request; resetting failed request counter to 0"
#                     - number.set:
#                         id: failed_requests
#                         value: 0
#           on_error:
#             then:
#               # - lambda: |-
#               #     ESP_LOGD("main", "request failed");
#               - logger.log: "Request failed!"
#               - number.increment: failed_requests
#               - logger.log:
#                   format: "Int %f %d"
#                   args: ['id(failed_requests).state', 'static_cast<int>(id(failed_requests).state)']



# number:
#   - platform: template
#     id: failed_requests
#     name: Failed Requests
#     optimistic: True
#     restore_value: True
#     min_value: 0
#     max_value: 10000
#     step: 1
#     on_value:
#       then:
#         - lambda: |-
#             int val = static_cast<int>(x);
#             if (val == 1024) {
#               ESP_LOGW("main", "resetting %d", val);
#               auto call = id(failed_requests).make_call();
#               call.set_value(val >> 1);
#               call.perform();
#               return;
#             }
#             bool should_reset = val && (( val & (val - 1)) == 0);
#             if (should_reset) {
#               ESP_LOGW("main", "POWER CYCLING %d", should_reset);
#               id(power_cycle).execute();
#               ESP_LOGW("main", "NOT DONE POWER CYCLING %d", should_reset);
#             }


# number:
#   - platform: template
#     id: failed_requests
#     name: Failed Requests
#     optimistic: True
#     restore_value: True
#     min_value: 0
#     max_value: 10000
#     step: 1
#     on_value:


# sensor:
#   - platform: hlw8012
#     sel_pin:g
#       number: GPIO20
#       inverted: true
#     cf_pin: GPIO18
#     cf1_pin: GPIO19
#     model: BL0937
#     current_resistor: 0.0011
#     voltage_divider: 1450
#     current:
#       name: Amps
#     voltage:
#       name: Volts
#     power:
#       name: Watts
#       accuracy_decimals: 0
#     energy:
#       name: Energy
#     update_interval: 3s
#     change_mode_every: 4

switch:
  - platform: gpio
    name: Relay
    id: relay
    device_class: outlet
    pin: GPIO6
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.turn_on: white_led
    on_turn_off:
      then:
        - light.turn_off: white_led


binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay

light:
  - platform: binary
    internal: true
    name: White LED
    id: white_led
    output: white_output
    restore_mode: ALWAYS_ON

  - platform: status_led
    name: "Device Status"
    id: device_status_led
    pin:
      number: GPIO8
      inverted: True
    internal: True


# status_led:
#   pin:
#     number: GPIO8
#     inverted: true

output:
  - id: white_output
    platform: gpio
    pin: GPIO7
    inverted: true






script:
  - id: make_http_request
    then:
      - http_request.get:
          url: https://www.google.com/generate_204
          on_response:
            then:
              script.execute: http_request_success
          on_error:
            then:
              script.execute: http_request_failure

  - id: http_request_success
    then:
      - lambda: |-
          id(failed_requests) = 0;
          id(failed_requests_no_api_client) = 0;

          int now = (int) id(plug_uptime).state;
          int last_power_cycle_seconds = now - id(last_power_cycle);
          ESP_LOGD("internet_watchdog", "%d consecutive failed requests; %d power cycles; %d seconds of uptime; %d seconds since last power cycle", id(failed_requests), id(power_cycle_cnt), now, last_power_cycle_seconds);

    #   - logger.log:
    #     level: DEBUG
    #     format: 'Successful HTTP response'
    #     # args:
    #     #   - response->status_code
    #     #   - response->duration_ms
    # - if:
    #     condition:
    #       lambda: 'return id(failed_requests).state > 0;'
    #     then:
    #       - logger.log:
    #           level: INFO
    #           format: "Successful request; resetting failed request counter to 0"
    #       - number.set:
    #           id: failed_requests
    #           value: 0

  - id: http_request_failure
    then:
      - lambda: |-
          int now = (int) id(plug_uptime).state;
          /*
          Repeat power cycling can be really aggressive, especially since the power is down for 45 seconds but that is asynchronous to
          the HTTP timer. (Ie, the next HTTP request will happen 15 seconds after the power is cycled.) And we don't expect internet to be
          working while the routers boot back up.
          Failed HTTP requests within the first 90 seconds *after* the power cycle is completed won't increment the failed requests counter.
          Realistically, this means the first 2 minutes.
          */
          int last_power_cycle_seconds = now - id(last_power_cycle);
          if (last_power_cycle_seconds < (45 + 90)) {
            ESP_LOGI("internet_watchdog", "Request failed but last power cycle was only %d seconds ago so this doesn't even count", last_power_cycle_seconds);
            return;
          }

          id(failed_requests) += 1;



          ESP_LOGI("internet_watchdog", "Request Failed! %d consecutive failed requests; %d power cycles; %d seconds of uptime; %d seconds since last power cycle", id(failed_requests), id(power_cycle_cnt), now, last_power_cycle_seconds);

          if (id(api_component).is_connected()) {
            id(failed_requests_no_api_client) = 0;
          } else {
            id(failed_requests_no_api_client) += 1;
          }

          if (id(failed_requests) > 3) {
            if (! id(relay).state) {
              ESP_LOGD("internet_watchdog", "Skipping power cycle because switch is currently off");
              return;
            }

            if (now < (5 * 60)) {
              ESP_LOGD("internet_watchdog", "Skipping power cycle during first 5 minutes after boot");
              return;
            }

            /*
            A simple backkoff strategy.
            After the first power cycle, if the internet is actually down then power cycling frequently doesn't seem
            to be working, and is disruptive to local devices. If the internet isn't down (false negative) then power cycling
            is disruptive to actual connectivity.
            *After* the first 3 consecutive failed requests and 10 minutes after boot (above), only powercycle if the failed
            request count (aka number of minutes) is a power of 2: 2 (skipped), 4, 8, 16, 32, 64, 128, 256, 512
            That's total minutes, not minutes since last power cycle. E.g, 32 happens 16 minutes after previous reboot.
            After 512 consecutive minutes, reboot every 4 hours -- so 752, 992, etc....
            This can overlap with the initial 5 minute wait. E.g., if all requests fail then first power cycle is after 8 minutes.
            */
            int fr = id(failed_requests);
            bool pow_of_two = fr && (( fr & (fr - 1)) == 0);
            bool should_reset = (fr <= 512 && pow_of_two) || (fr > 512 && (fr - 512) % 240 == 0);

            if (! should_reset) {
              ESP_LOGD("internet_watchdog", "Skipping power cycle because %d is not a power of 2 or every 4 hours after 8.5 hours ((x - 512) %% 240 == 0)", fr);
              return;
            }

            if (true || id(failed_requests_no_api_client) > 20) {
              ESP_LOGI("internet_watchdog", "NOT ... Rebooting the switch");
              //id(cycle_and_reboot).execute();
              //return;
            }

            ESP_LOGI("internet_watchdog", "Power cycling the relay after %d consecutive failures", fr);
            id(last_power_cycle) = now;
            id(cycle_power).execute();
          }

  - id: cycle_power
    then:
      - lambda: id(power_cycle_cnt) += 1;
      - switch.turn_off: relay
      - delay: 45s
      - switch.turn_on: relay

  # Cycle
  - id: cycle_and_reboot
    then:
      - switch.turn_off: relay
      - delay: 45s
      - button.press: reboot_btn
